enum MessageType {
  authRequest,
  authResponse,
  authChallenge,
  listSchedules,
  scheduleList,
  updateSchedule,
  executeSchedule,
  scheduleUpdated,
  cancelSchedule,
  scheduleCancelled,
  backupProgress,
  backupStep,
  backupComplete,
  backupFailed,
  listFiles,
  fileList,
  fileTransferStart,
  fileChunk,
  fileTransferProgress,
  fileTransferComplete,
  fileTransferError,
  fileAck,
  metricsRequest,
  metricsResponse,
  heartbeat,
  disconnect,
  error,
  // Adicionados ao final do enum para preservar indices (wire-compat).
  // Cliente legado que receber esses tipos cai no fallback
  // `MessageType.error` em `BinaryProtocol.deserializeMessage`,
  // sem quebrar a deserializacao (ver ADR-003).
  capabilitiesRequest,
  capabilitiesResponse,
  healthRequest,
  healthResponse,
  sessionRequest,
  sessionResponse,
}
