import 'dart:io';

const List<String> _generatedSuffixes = <String>[
  '.g.dart',
  '.freezed.dart',
  '.mocks.dart',
];

const Map<String, String> _sgbdAreas = <String, String>{
  'SQL Server': 'sql_server',
  'PostgreSQL': 'postgres',
  'Sybase': 'sybase',
  'Firebird': 'firebird',
};

const List<String> _prECorePaths = <String>[
  'lib/domain/entities/database_connection_config.dart',
  'lib/core/di/sgbd_registration.dart',
  'lib/infrastructure/repositories/base_database_config_repository.dart',
  'lib/application/providers/database_config_provider_base.dart',
  'lib/application/services/strategies/generic_database_backup_strategy.dart',
];

void main(List<String> args) {
  final bool markdown = args.contains('--markdown');
  final Directory libRoot = Directory('lib');
  if (!libRoot.existsSync()) {
    stderr.writeln('Run from repository root (lib/ not found).');
    exitCode = 1;
    return;
  }

  final Map<String, _AreaStats> stats = <String, _AreaStats>{};
  for (final MapEntry<String, String> area in _sgbdAreas.entries) {
    stats[area.key] = _AreaStats();
  }
  final _AreaStats prECore = _AreaStats();

  for (final FileSystemEntity entity in libRoot.listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) {
      continue;
    }
    final String normalized = entity.path.replaceAll(r'\', '/');
    if (_isGenerated(normalized)) {
      continue;
    }
    final int lines = _countLines(entity);
    final String lower = normalized.toLowerCase();

    for (final MapEntry<String, String> area in _sgbdAreas.entries) {
      if (lower.contains(area.value)) {
        stats[area.key]!.add(entity.path, lines);
      }
    }

    for (final String corePath in _prECorePaths) {
      if (normalized.endsWith(corePath)) {
        prECore.add(entity.path, lines);
        break;
      }
    }
  }

  if (markdown) {
    _printMarkdown(stats, prECore);
    return;
  }

  stdout.writeln('SGBD LOC report (lib/**/*.dart, excluding generated)');
  stdout.writeln('Generated: ${DateTime.now().toIso8601String()}');
  stdout.writeln('');
  for (final MapEntry<String, _AreaStats> entry in stats.entries) {
    stdout.writeln(
      '${entry.key} (${_sgbdAreas[entry.key]}): '
      '${entry.value.fileCount} files, ${entry.value.lineCount} lines',
    );
  }
  stdout.writeln(
    'PR-E core (${_prECorePaths.length} files): '
    '${prECore.fileCount} files, ${prECore.lineCount} lines',
  );
  stdout.writeln('');
  stdout.writeln(
    'Markdown table: dart run tools/sgbd_loc_report.dart --markdown',
  );
  stdout.writeln('');
  stdout.writeln('Diff vs base branch (example):');
  stdout.writeln(
    '  git diff --stat origin/main...HEAD -- lib/domain lib/application '
    'lib/infrastructure lib/presentation',
  );
}

void _printMarkdown(Map<String, _AreaStats> stats, _AreaStats prECore) {
  stdout.writeln('<!-- Generated by: dart run tools/sgbd_loc_report.dart -->');
  stdout.writeln('');
  stdout.writeln('| Área | Arquivos | Linhas (~) |');
  stdout.writeln('|------|----------|------------|');
  for (final MapEntry<String, _AreaStats> entry in stats.entries) {
    final String slug = _sgbdAreas[entry.key]!;
    stdout.writeln(
      '| ${entry.key} (`…$slug…`) | ${entry.value.fileCount} | '
      '${entry.value.lineCount} |',
    );
  }
  stdout.writeln(
    '| Núcleo PR-E (${_prECorePaths.length} arquivos listados no plano) | '
    '${prECore.fileCount} | ${prECore.lineCount} |',
  );
}

bool _isGenerated(String normalizedPath) {
  for (final String suffix in _generatedSuffixes) {
    if (normalizedPath.endsWith(suffix)) {
      return true;
    }
  }
  return normalizedPath.contains('/generated/') ||
      normalizedPath.contains('/gen/');
}

int _countLines(File file) {
  return file.readAsLinesSync().length;
}

class _AreaStats {
  int fileCount = 0;
  int lineCount = 0;

  void add(String path, int lines) {
    fileCount++;
    lineCount += lines;
  }
}
