import 'package:backup_database/core/encryption/encryption_service.dart';
import 'package:flutter_test/flutter_test.dart';

/// Ciphertexts produced with `encrypt` 5.0.3 (AES-SIC/PKCS7, IV
/// `BackupDatabaseIV`) before that package was removed.
const _goldenPlaintext = 'golden-plaintext-v1';
const _goldenDeviceKey = 'test-device-key-for-golden';
const _goldenLegacyCiphertext = 'KNBoGVmO5GJ7DkVysgbpKi8Tg88Jmhz+UbqCSmZhHYU=';
const _goldenDeviceCiphertext = 'ysS8qw7YGB8xJxteX6kLdkEUzvTLrvpXHIRJIEHuh0s=';

void main() {
  tearDown(EncryptionService.resetToLegacy);

  group('EncryptionService with legacy key', () {
    test('should round-trip plaintext', () {
      const plaintext = 'nextcloud-app-password';

      final encrypted = EncryptionService.encrypt(plaintext);

      expect(encrypted, isNot(equals(plaintext)));
      expect(EncryptionService.decrypt(encrypted), equals(plaintext));
    });

    test('should decrypt ciphertext generated by encrypt 5.0.3', () {
      expect(
        EncryptionService.decrypt(_goldenLegacyCiphertext),
        equals(_goldenPlaintext),
      );
    });

    test('should skip encrypting empty string', () {
      expect(EncryptionService.encrypt(''), isEmpty);
      expect(EncryptionService.decrypt(''), isEmpty);
    });

    test('should return non-base64 text unchanged on decrypt', () {
      const plain = 'not-base64';
      expect(EncryptionService.decrypt(plain), equals(plain));
    });

    test('should not double-encrypt already encrypted text', () {
      const plaintext = 'once-only';
      final first = EncryptionService.encrypt(plaintext);
      final second = EncryptionService.encrypt(first);

      expect(second, equals(first));
      expect(EncryptionService.decrypt(second), equals(plaintext));
    });

    test('should report legacy as key source by default', () {
      expect(EncryptionService.getKeySource(), equals('legacy'));
    });
  });

  group('EncryptionService with device key', () {
    setUp(() {
      EncryptionService.initializeWithDeviceKey(_goldenDeviceKey);
    });

    test('should round-trip plaintext with device key', () {
      const plaintext = 'oauth-refresh-token';

      final encrypted = EncryptionService.encrypt(plaintext);

      expect(encrypted, isNot(equals(plaintext)));
      expect(EncryptionService.decrypt(encrypted), equals(plaintext));
      expect(EncryptionService.getKeySource(), equals('device'));
    });

    test('should decrypt ciphertext generated by encrypt 5.0.3', () {
      expect(
        EncryptionService.decrypt(_goldenDeviceCiphertext),
        equals(_goldenPlaintext),
      );
    });

    test('should fall back to legacy key when current key fails', () {
      expect(
        EncryptionService.decrypt(_goldenLegacyCiphertext),
        equals(_goldenPlaintext),
      );
    });
  });

  group('EncryptionService.hashPassword', () {
    test('should return SHA-256 hex digest', () {
      expect(
        EncryptionService.hashPassword('password'),
        equals(
          '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
        ),
      );
    });
  });
}
